# Generated by Django 5.1.1 on 2024-12-09 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('marks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marks.grade'),
        ),
        migrations.AddField(
            model_name='student',
            name='progress',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='marks.progressstudent'),
        ),
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(blank=True, to='account.student'),
        ),
    ]
