# Generated by Django 5.1.1 on 2024-12-09 13:59

import django.db.models.deletion
import django_editorjs_fields.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('title', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lesson_type', models.CharField(choices=[('Lesson', 'Урок'), ('SAU', 'СОР'), ('SAT', 'СОЧ')], max_length=6)),
                ('content', django_editorjs_fields.fields.EditorJsJSONField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='Lessons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('russian', 'Русский'), ('kazakh', 'Казахский')], max_length=9)),
                ('lessons', models.ManyToManyField(to='lesson.lesson')),
            ],
        ),
        migrations.CreateModel(
            name='SummativeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answers', models.JSONField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lesson.lesson')),
            ],
        ),
    ]
