# Generated by Django 5.1.1 on 2024-12-09 13:59

import django.core.validators
import django.db.models.deletion
import marks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('lesson', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgressQuarterStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('current', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ProgressSubjectStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('final_score', models.IntegerField(blank=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
            ],
        ),
        migrations.CreateModel(
            name='AttachedFileStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=marks.models.user_directory_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lesson.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.student')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressPeriodStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current', models.BooleanField(default=False)),
                ('name', models.CharField(max_length=9)),
                ('quarters', models.ManyToManyField(to='marks.progressquarterstudent')),
            ],
        ),
        migrations.CreateModel(
            name='ProgressStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periods', models.ManyToManyField(to='marks.progressperiodstudent')),
            ],
        ),
        migrations.AddField(
            model_name='progressquarterstudent',
            name='subjects',
            field=models.ManyToManyField(to='marks.progresssubjectstudent'),
        ),
        migrations.CreateModel(
            name='ProgressSummativeAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.student')),
                ('summative_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lesson.summativeassessment')),
            ],
        ),
        migrations.CreateModel(
            name='Quarter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('first', 'Первая четверть'), ('second', 'Вторая четверть'), ('third', 'Третья четверть'), ('fourth', 'Четвертая четверть')], max_length=25)),
                ('lessons', models.ManyToManyField(to='lesson.lessons')),
            ],
        ),
        migrations.AddField(
            model_name='progressquarterstudent',
            name='quarter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marks.quarter'),
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('algebra', 'Алгебра'), ('english_language', 'Английский язык'), ('biology', 'Биология'), ('history', 'Всемирная история'), ('geography', 'География'), ('geometry', 'Геометрия'), ('informatics', 'Информатика'), ('kazakh_history', 'История Казахстана'), ('kazakh_language_and_literature', 'Казахский язык и литература'), ('business', 'Основы предпринимательства и бизнеса'), ('russian_literature', 'Русская литература'), ('russian_language', 'Русский язык'), ('physics', 'Физика'), ('chemistry', 'Химия'), ('wellness', 'Wellness')], max_length=30)),
                ('quarters', models.ManyToManyField(to='marks.quarter')),
            ],
        ),
        migrations.AddField(
            model_name='progresssubjectstudent',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marks.subject'),
        ),
        migrations.CreateModel(
            name='ProgressLatestLessonStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='lesson.lesson')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='account.student')),
                ('quarter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marks.quarter')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='marks.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(7), django.core.validators.MaxValueValidator(11)])),
                ('direction', models.CharField(blank=True, choices=[('EM', 'Естественно-математический'), ('OG', 'Общественно-гуманитарный')], max_length=255, null=True)),
                ('subjects', models.ManyToManyField(to='marks.subject')),
            ],
        ),
    ]
