# Generated by Django 5.1.1 on 2024-12-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marks', '0002_alter_progresssubjectstudent_final_score'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='progressquarterstudent',
            name='current',
        ),
        migrations.AddField(
            model_name='quarter',
            name='current',
            field=models.BooleanField(default=False),
        ),
    ]
